 /run/initialize
/vis/open OGL
/vis/drawVolume    
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set C12 blue
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set e- green
/vis/modeling/trajectories/drawByParticleID-0/set e+ green
/vis/modeling/trajectories/drawByParticleID-0/set gamma red
/vis/scene/add/trajectories
/vis/scene/add/scale 10 cm
#/vis/scene/add/axes
/vis/scene/add/eventID
 /vis/scene/endOfEventAction accumulate
